/**
 * Buchungskarten (Booking Cards) translations for all languages
 */

export const buchungskartenTranslations = {
    de: {
        // Page title and overview
        title: 'Buchungskarten Übersicht',
        overview: 'Buchungskarten Übersicht',
        
        // Form labels and placeholders
        descriptionPlaceholder: 'Geben Sie hier die Beschreibung der Buchung ein...',
        selectImage: 'Bild auswählen (optional):',
        selectCategory: '-- Bitte Kategorie auswählen --',
        selectBookingType: 'Buchungsart wählen',
        noImage: '-- Kein Bild auswählen --',
        
        // Authentication and validation
        noAuthFound: 'Keine Authentifizierung gefunden. Bitte melden Sie sich an.',
        pleaseSelectBookingType: 'Bitte wählen Sie eine Buchungsart aus.',
        pleaseEnterDate: 'Bitte geben Sie ein Datum ein.',
        pleaseSelectCategory: 'Bitte wählen Sie eine Kategorie aus.',
        pleaseEnterDescription: 'Bitte geben Sie eine Beschreibung ein.',
        pleaseEnterValidAmount: 'Bitte geben Sie einen gültigen Betrag ein.',
        pleaseSelectDocument: 'Bitte wählen Sie ein Beleg-Dokument aus.',
        
        // Error messages
        errorLoadingCategories: 'Fehler beim Laden der Kategorien. Bitte versuchen Sie es später erneut.',
        errorLoadingImages: 'Fehler beim Laden der Bilder. Bitte versuchen Sie es später erneut.',
        errorLoadingBookings: 'Fehler beim Laden der Buchungskarten: ',
        errorDeleting: 'Fehler beim Löschen: ',
        
        // Empty states
        noBookings: 'Keine Buchungskarten vorhanden',
        
        // Confirmations
        confirmDelete: 'Möchten Sie diese Buchung wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
        bookingDeleted: 'Buchung erfolgreich gelöscht',
        
        // Actions
        deleteBooking: 'Buchung löschen',
        
        // Evaluation section
        loadExistingEvaluations: 'Vorhandene Auswertungen laden',
        evaluationTitle: 'Leer lassen für automatischen Titel',
        pleaseEnterDates: 'Bitte geben Sie sowohl ein Start- als auch ein Enddatum an.',
        taxPayable: 'Abzuführende USt',
        taxRefundable: 'Erstattungsfähige USt',
        listBookings: 'List Buchungen',
        noEvaluationsFound: 'Keine Auswertungen gefunden.',
        existingEvaluations: 'Vorhandene Auswertungen',
        noBookingsInPeriod: 'Keine Buchungen im ausgewählten Zeitraum gefunden.',
        bookingsForCard: 'Buchungen für',
        
        // Evaluation page
        evaluationsPageTitle: 'Buchungskarten Auswertungen',
        createNewEvaluation: 'Neue Auswertung erstellen',
        periodType: 'Zeitraum-Typ:',
        dateFrom: 'Datum Von:',
        dateTo: 'Datum Bis:',
        titleOptional: 'Titel (optional):',
        createEvaluation: 'Auswertung erstellen',
        
        // Period types
        periodTypes: {
            TAG: 'Tag',
            WOCHE: 'Woche',
            MONAT: 'Monat',
            QUARTAL: 'Quartal',
            JAHR: 'Jahr',
            BENUTZERDEFINIERT: 'Benutzerdefiniert'
        },
        
        // Evaluation display
        period: 'Zeitraum:',
        type: 'Typ:',
        to: 'bis',
        income: 'Einnahmen',
        expenses: 'Ausgaben',
        balance: 'Saldo',
        bookings: 'Buchungen',
        totalBookings: 'Buchungen gesamt',
        outgoingVat: 'Ausgangs-USt',
        incomingVat: 'Eingangs-USt',
        vatBalance: 'USt-Saldo',
        vatFromIncome: 'USt aus Einnahmen',
        vatFromExpenses: 'USt aus Ausgaben',
        
        // Expandable booking view
        from: 'vom',
        receipt: 'Beleg:',
        document: 'Dokument:',
        image: 'Bild:',
        clickFor: 'Klicken für',
        pdfView: 'PDF-Ansicht',
        download: 'Download',
        
        // PDF Report
        pdfReport: 'PDF Report',
        delete: 'Löschen',
        pdfReportCreating: 'PDF Report wird erstellt...',
        
        // PDF Report Template
        evaluationReport: 'Buchungsauswertung',
        periodLabel: 'Zeitraum:',
        createdOn: 'Erstellt am:',
        bookingsDescending: 'Buchungen (sortiert nach Datum absteigend)',
        bookingsTotal: 'Buchungen total',
        autoGenerated: 'Dieser Report wurde automatisch generiert vom Buchungskarten-System',
        status: 'Stand:',
        
        // Table headers for PDF
        pdfTableHeaders: {
            date: 'Datum',
            type: 'Art',
            category: 'Kategorie',
            description: 'Beschreibung',
            amount: 'Betrag',
            receiptNumber: 'Belegnummer',
            vatRate: 'USt-Satz',
            vatAmount: 'USt-Betrag',
            document: 'Dokument'
        },
        
        // PDF and popup
        popupBlocker: 'Popup-Blocker verhindert die PDF-Erstellung. Bitte erlauben Sie Popups für diese Seite.',
        invalidDocument: 'Ungültiges Dokument.',
        
        // Delete evaluation
        confirmDeleteEvaluation: 'Möchten Sie diese Auswertung wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
        evaluationDeleted: 'Auswertung erfolgreich gelöscht',
        errorDeletingEvaluation: 'Fehler beim Löschen der Auswertung: ',
        
        // Modal and form actions
        close: 'Schließen',
        cannotChangeId: 'Die ID kann nicht geändert werden',
        selectBookingTypeFirst: 'Erst Buchungsart wählen',
        selectCategoryLabel: 'Kategorie wählen',
        
        // Additional error messages
        errorCreatingEvaluation: 'Fehler beim Erstellen der Auswertung',
        errorLoadingEvaluations: 'Fehler beim Laden der Auswertungen',
        errorDownloading: 'Fehler beim Download',
        
        // Form labels
        createNewBookingCard: 'Neue Buchungskarte erstellen',
        bookingType: 'Buchungsart:',
        date: 'Datum:',
        category: 'Kategorie:',
        description: 'Beschreibung:',
        amount: 'Betrag (€):',
        receiptNumber: 'Belegnummer (optional):',
        vatRate: 'USt-Satz (%) (optional):',
        vatAmount: 'USt-Betrag (€) (optional):',
        receiptDocument: 'Beleg-Dokument:',
        selectImageLabel: 'Bild auswählen (optional):',
        save: 'Speichern',
        chooseFile: 'Datei auswählen',
        noFileSelected: 'Keine Datei ausgewählt',
        editBooking: 'Buchung bearbeiten',
        
        // Edit overlay
        editBookingTitle: '✏️ Buchungskarte bearbeiten',
        cancel: 'Abbrechen',
        currentDocument: 'Aktuelles Dokument:',
        cannotChangeIdDescription: 'Die ID kann nicht geändert werden',
        
        // Form labels for edit overlay
        editLabels: {
            id: 'ID',
            date: 'Datum',
            description: 'Beschreibung',
            amount: 'Betrag (€)',
            receiptNumber: 'Belegnummer',
            vatRate: 'USt-Satz (%)',
            vatAmount: 'USt-Betrag (€)',
            bookingType: 'Buchungsart',
            category: 'Kategorie',
            receiptDocument: 'Beleg-Dokument',
            imageOptional: 'Bild (optional)'
        },
        
        // Overview page
        overviewTitle: 'Buchungskarten Übersicht',
        loading: 'Lade Buchungskarten...',
        noAuthForTable: 'Keine Authentifizierung gefunden. Bitte melden Sie sich an.',
        errorLoadingBookingsTable: 'Fehler beim Laden der Buchungskarten',
        
        // Table headers
        tableHeaders: {
            id: 'ID',
            date: 'Datum',
            bookingType: 'Buchungsart',
            category: 'Kategorie',
            description: 'Beschreibung',
            amount: 'Betrag (€)',
            receiptNumber: 'Belegnummer',
            vatRate: 'USt-Satz (%)',
            vatAmount: 'USt-Betrag (€)',
            document: 'Dokument',
            image: 'Bild',
            created: 'Erstellt',
            actions: 'Aktionen'
        },
        
        // Enum translations
        // BuchungsArt
        buchungsArt: {
            EINNAHME: 'Einnahme',
            AUSGABE: 'Ausgabe'
        },
        
        // BuchungsKategorie
        buchungsKategorie: {
            // Einnahmen
            VERKAUF: 'Verkauf',
            DIENSTLEISTUNG: 'Dienstleistung',
            ZINSEN: 'Zinsen',
            SONSTIGE_EINNAHMEN: 'Sonstige Einnahmen',
            
            // Ausgaben
            BUEROKOSTEN: 'Bürokosten',
            REISEKOSTEN: 'Reisekosten',
            MARKETING: 'Marketing',
            MIETE: 'Miete',
            STROM: 'Strom',
            TELEFON: 'Telefon',
            VERSICHERUNG: 'Versicherung',
            SOFTWARE_LIZENZ_GEBUEHR: 'Software Lizenz/Gebühr',
            SERVER_SOFTWARE_HOSTING: 'Server/Software Hosting',
            SONSTIGE_AUSGABEN: 'Sonstige Ausgaben'
        }
    },
    
    en: {
        // Page title and overview
        title: 'Booking Cards Overview',
        overview: 'Booking Cards Overview',
        
        // Form labels and placeholders
        descriptionPlaceholder: 'Enter the booking description here...',
        selectImage: 'Select image (optional):',
        selectCategory: '-- Please select category --',
        selectBookingType: 'Select booking type',
        noImage: '-- Select no image --',
        
        // Authentication and validation
        noAuthFound: 'No authentication found. Please sign in.',
        pleaseSelectBookingType: 'Please select a booking type.',
        pleaseEnterDate: 'Please enter a date.',
        pleaseSelectCategory: 'Please select a category.',
        pleaseEnterDescription: 'Please enter a description.',
        pleaseEnterValidAmount: 'Please enter a valid amount.',
        pleaseSelectDocument: 'Please select a document.',
        
        // Error messages
        errorLoadingCategories: 'Error loading categories. Please try again later.',
        errorLoadingImages: 'Error loading images. Please try again later.',
        errorLoadingBookings: 'Error loading booking cards: ',
        errorDeleting: 'Error deleting: ',
        
        // Empty states
        noBookings: 'No booking cards available',
        
        // Confirmations
        confirmDelete: 'Do you really want to delete this booking? This action cannot be undone.',
        bookingDeleted: 'Booking successfully deleted',
        
        // Actions
        deleteBooking: 'Delete Booking',
        
        // Evaluation section
        loadExistingEvaluations: 'Load existing evaluations',
        evaluationTitle: 'Leave empty for automatic title',
        pleaseEnterDates: 'Please enter both start and end dates.',
        taxPayable: 'Tax payable',
        taxRefundable: 'Tax refundable',
        listBookings: 'List bookings',
        noEvaluationsFound: 'No evaluations found.',
        existingEvaluations: 'Existing evaluations',
        noBookingsInPeriod: 'No bookings found in the selected period.',
        bookingsForCard: 'Bookings for',
        
        // Evaluation page
        evaluationsPageTitle: 'Booking Cards Evaluations',
        createNewEvaluation: 'Create New Evaluation',
        periodType: 'Period Type:',
        dateFrom: 'Date From:',
        dateTo: 'Date To:',
        titleOptional: 'Title (optional):',
        createEvaluation: 'Create Evaluation',
        
        // Period types
        periodTypes: {
            TAG: 'Day',
            WOCHE: 'Week',
            MONAT: 'Month',
            QUARTAL: 'Quarter',
            JAHR: 'Year',
            BENUTZERDEFINIERT: 'Custom'
        },
        
        // Evaluation display
        period: 'Period:',
        type: 'Type:',
        to: 'to',
        income: 'Income',
        expenses: 'Expenses',
        balance: 'Balance',
        bookings: 'bookings',
        totalBookings: 'total bookings',
        outgoingVat: 'Output VAT',
        incomingVat: 'Input VAT',
        vatBalance: 'VAT Balance',
        vatFromIncome: 'VAT from income',
        vatFromExpenses: 'VAT from expenses',
        
        // Expandable booking view
        from: 'from',
        receipt: 'Receipt:',
        document: 'Document:',
        image: 'Image:',
        clickFor: 'Click for',
        pdfView: 'PDF view',
        download: 'Download',
        
        // PDF Report
        pdfReport: 'PDF Report',
        delete: 'Delete',
        pdfReportCreating: 'Creating PDF report...',
        
        // PDF Report Template
        evaluationReport: 'Accounting Report',
        periodLabel: 'Period:',
        createdOn: 'Created on:',
        bookingsDescending: 'Bookings (sorted by date descending)',
        bookingsTotal: 'total bookings',
        autoGenerated: 'This report was automatically generated by the Booking Cards System',
        status: 'Status:',
        
        // Table headers for PDF
        pdfTableHeaders: {
            date: 'Date',
            type: 'Type',
            category: 'Category',
            description: 'Description',
            amount: 'Amount',
            receiptNumber: 'Receipt Number',
            vatRate: 'VAT Rate',
            vatAmount: 'VAT Amount',
            document: 'Document'
        },
        
        // PDF and popup
        popupBlocker: 'Popup blocker prevents PDF creation. Please allow popups for this site.',
        invalidDocument: 'Invalid document.',
        
        // Delete evaluation
        confirmDeleteEvaluation: 'Do you really want to delete this evaluation? This action cannot be undone.',
        evaluationDeleted: 'Evaluation successfully deleted',
        errorDeletingEvaluation: 'Error deleting evaluation: ',
        
        // Modal and form actions
        close: 'Close',
        cannotChangeId: 'The ID cannot be changed',
        selectBookingTypeFirst: 'Select booking type first',
        selectCategoryLabel: 'Select category',
        
        // Additional error messages
        errorCreatingEvaluation: 'Error creating evaluation',
        errorLoadingEvaluations: 'Error loading evaluations',
        errorDownloading: 'Error downloading',
        
        // Form labels
        createNewBookingCard: 'Create New Booking Card',
        bookingType: 'Booking Type:',
        date: 'Date:',
        category: 'Category:',
        description: 'Description:',
        amount: 'Amount (€):',
        receiptNumber: 'Receipt Number (optional):',
        vatRate: 'VAT Rate (%) (optional):',
        vatAmount: 'VAT Amount (€) (optional):',
        receiptDocument: 'Receipt Document:',
        selectImageLabel: 'Select Image (optional):',
        save: 'Save',
        chooseFile: 'Choose File',
        noFileSelected: 'No file selected',
        editBooking: 'Edit Booking',
        
        // Edit overlay
        editBookingTitle: '✏️ Edit Booking Card',
        cancel: 'Cancel',
        currentDocument: 'Current Document:',
        cannotChangeIdDescription: 'The ID cannot be changed',
        
        // Form labels for edit overlay
        editLabels: {
            id: 'ID',
            date: 'Date',
            description: 'Description',
            amount: 'Amount (€)',
            receiptNumber: 'Receipt Number',
            vatRate: 'VAT Rate (%)',
            vatAmount: 'VAT Amount (€)',
            bookingType: 'Booking Type',
            category: 'Category',
            receiptDocument: 'Receipt Document',
            imageOptional: 'Image (optional)'
        },
        
        // Overview page
        overviewTitle: 'Booking Cards Overview',
        loading: 'Loading booking cards...',
        noAuthForTable: 'No authentication found. Please sign in.',
        errorLoadingBookingsTable: 'Error loading booking cards',
        
        // Table headers
        tableHeaders: {
            id: 'ID',
            date: 'Date',
            bookingType: 'Booking Type',
            category: 'Category',
            description: 'Description',
            amount: 'Amount (€)',
            receiptNumber: 'Receipt Number',
            vatRate: 'VAT Rate (%)',
            vatAmount: 'VAT Amount (€)',
            document: 'Document',
            image: 'Image',
            created: 'Created',
            actions: 'Actions'
        },
        
        // Enum translations
        // BuchungsArt
        buchungsArt: {
            EINNAHME: 'Income',
            AUSGABE: 'Expense'
        },
        
        // BuchungsKategorie
        buchungsKategorie: {
            // Einnahmen
            VERKAUF: 'Sales',
            DIENSTLEISTUNG: 'Services',
            ZINSEN: 'Interest',
            SONSTIGE_EINNAHMEN: 'Other Income',
            
            // Ausgaben
            BUEROKOSTEN: 'Office Costs',
            REISEKOSTEN: 'Travel Expenses',
            MARKETING: 'Marketing',
            MIETE: 'Rent',
            STROM: 'Electricity',
            TELEFON: 'Phone',
            VERSICHERUNG: 'Insurance',
            SOFTWARE_LIZENZ_GEBUEHR: 'Software License/Fee',
            SERVER_SOFTWARE_HOSTING: 'Server/Software Hosting',
            SONSTIGE_AUSGABEN: 'Other Expenses'
        }
    },
    
    fr: {
        // Page title and overview
        title: 'Aperçu des cartes de réservation',
        overview: 'Aperçu des cartes de réservation',
        
        // Form labels and placeholders
        descriptionPlaceholder: 'Entrez ici la description de la réservation...',
        selectImage: 'Sélectionner une image (optionnel):',
        selectCategory: '-- Veuillez sélectionner une catégorie --',
        selectBookingType: 'Sélectionner le type de réservation',
        noImage: '-- Ne sélectionner aucune image --',
        
        // Authentication and validation
        noAuthFound: 'Aucune authentification trouvée. Veuillez vous connecter.',
        pleaseSelectBookingType: 'Veuillez sélectionner un type de réservation.',
        pleaseEnterDate: 'Veuillez entrer une date.',
        pleaseSelectCategory: 'Veuillez sélectionner une catégorie.',
        pleaseEnterDescription: 'Veuillez entrer une description.',
        pleaseEnterValidAmount: 'Veuillez entrer un montant valide.',
        pleaseSelectDocument: 'Veuillez sélectionner un document.',
        
        // Error messages
        errorLoadingCategories: 'Erreur lors du chargement des catégories. Veuillez réessayer plus tard.',
        errorLoadingImages: 'Erreur lors du chargement des images. Veuillez réessayer plus tard.',
        errorLoadingBookings: 'Erreur lors du chargement des cartes de réservation: ',
        errorDeleting: 'Erreur lors de la suppression: ',
        
        // Empty states
        noBookings: 'Aucune carte de réservation disponible',
        
        // Confirmations
        confirmDelete: 'Voulez-vous vraiment supprimer cette réservation? Cette action ne peut pas être annulée.',
        bookingDeleted: 'Réservation supprimée avec succès',
        
        // Actions
        deleteBooking: 'Supprimer la réservation',
        
        // Evaluation section
        loadExistingEvaluations: 'Charger les évaluations existantes',
        evaluationTitle: 'Laisser vide pour un titre automatique',
        pleaseEnterDates: 'Veuillez entrer les dates de début et de fin.',
        taxPayable: 'TVA à payer',
        taxRefundable: 'TVA remboursable',
        listBookings: 'Lister les réservations',
        noEvaluationsFound: 'Aucune évaluation trouvée.',
        existingEvaluations: 'Évaluations existantes',
        noBookingsInPeriod: 'Aucune réservation trouvée dans la période sélectionnée.',
        bookingsForCard: 'Réservations pour',
        
        // Evaluation page
        evaluationsPageTitle: 'Évaluations des cartes de réservation',
        createNewEvaluation: 'Créer une nouvelle évaluation',
        periodType: 'Type de période:',
        dateFrom: 'Date de début:',
        dateTo: 'Date de fin:',
        titleOptional: 'Titre (optionnel):',
        createEvaluation: 'Créer une évaluation',
        
        // Period types
        periodTypes: {
            TAG: 'Jour',
            WOCHE: 'Semaine',
            MONAT: 'Mois',
            QUARTAL: 'Trimestre',
            JAHR: 'Année',
            BENUTZERDEFINIERT: 'Personnalisé'
        },
        
        // Evaluation display
        period: 'Période:',
        type: 'Type:',
        to: 'à',
        income: 'Recettes',
        expenses: 'Dépenses',
        balance: 'Solde',
        bookings: 'réservations',
        totalBookings: 'réservations au total',
        outgoingVat: 'TVA collectée',
        incomingVat: 'TVA déductible',
        vatBalance: 'Solde TVA',
        vatFromIncome: 'TVA sur recettes',
        vatFromExpenses: 'TVA sur dépenses',
        
        // Expandable booking view
        from: 'du',
        receipt: 'Reçu:',
        document: 'Document:',
        image: 'Image:',
        clickFor: 'Cliquer pour',
        pdfView: 'vue PDF',
        download: 'Télécharger',
        
        // PDF Report
        pdfReport: 'Rapport PDF',
        delete: 'Supprimer',
        pdfReportCreating: 'Création du rapport PDF...',
        
        // PDF Report Template
        evaluationReport: 'Rapport comptable',
        periodLabel: 'Période:',
        createdOn: 'Créé le:',
        bookingsDescending: 'Réservations (triées par date décroissante)',
        bookingsTotal: 'réservations au total',
        autoGenerated: 'Ce rapport a été généré automatiquement par le système de cartes de réservation',
        status: 'État:',
        
        // Table headers for PDF
        pdfTableHeaders: {
            date: 'Date',
            type: 'Type',
            category: 'Catégorie',
            description: 'Description',
            amount: 'Montant',
            receiptNumber: 'Numéro de reçu',
            vatRate: 'Taux de TVA',
            vatAmount: 'Montant TVA',
            document: 'Document'
        },
        
        // PDF and popup
        popupBlocker: 'Le bloqueur de popup empêche la création de PDF. Veuillez autoriser les popups pour ce site.',
        invalidDocument: 'Document invalide.',
        
        // Delete evaluation
        confirmDeleteEvaluation: 'Voulez-vous vraiment supprimer cette évaluation? Cette action ne peut pas être annulée.',
        evaluationDeleted: 'Évaluation supprimée avec succès',
        errorDeletingEvaluation: 'Erreur lors de la suppression de l\'évaluation: ',
        
        // Modal and form actions
        close: 'Fermer',
        cannotChangeId: 'L\'ID ne peut pas être modifié',
        selectBookingTypeFirst: 'Sélectionnez d\'abord le type de réservation',
        selectCategoryLabel: 'Sélectionner une catégorie',
        
        // Additional error messages
        errorCreatingEvaluation: 'Erreur lors de la création de l\'\u00e9valuation',
        errorLoadingEvaluations: 'Erreur lors du chargement des évaluations',
        errorDownloading: 'Erreur lors du téléchargement',
        
        // Form labels
        createNewBookingCard: 'Créer une nouvelle carte de réservation',
        bookingType: 'Type de réservation:',
        date: 'Date:',
        category: 'Catégorie:',
        description: 'Description:',
        amount: 'Montant (€):',
        receiptNumber: 'Numéro de reçu (optionnel):',
        vatRate: 'Taux de TVA (%) (optionnel):',
        vatAmount: 'Montant TVA (€) (optionnel):',
        receiptDocument: 'Document de reçu:',
        selectImageLabel: 'Sélectionner une image (optionnel):',
        save: 'Enregistrer',
        chooseFile: 'Choisir un fichier',
        noFileSelected: 'Aucun fichier sélectionné',
        editBooking: 'Modifier la réservation',
        
        // Edit overlay
        editBookingTitle: '✏️ Modifier la carte de réservation',
        cancel: 'Annuler',
        currentDocument: 'Document actuel:',
        cannotChangeIdDescription: 'L\'ID ne peut pas être modifié',
        
        // Form labels for edit overlay
        editLabels: {
            id: 'ID',
            date: 'Date',
            description: 'Description',
            amount: 'Montant (€)',
            receiptNumber: 'Numéro de reçu',
            vatRate: 'Taux de TVA (%)',
            vatAmount: 'Montant TVA (€)',
            bookingType: 'Type de réservation',
            category: 'Catégorie',
            receiptDocument: 'Document de reçu',
            imageOptional: 'Image (optionnel)'
        },
        
        // Overview page
        overviewTitle: 'Aperçu des cartes de réservation',
        loading: 'Chargement des cartes de réservation...',
        noAuthForTable: 'Aucune authentification trouvée. Veuillez vous connecter.',
        errorLoadingBookingsTable: 'Erreur lors du chargement des cartes de réservation',
        
        // Table headers
        tableHeaders: {
            id: 'ID',
            date: 'Date',
            bookingType: 'Type de réservation',
            category: 'Catégorie',
            description: 'Description',
            amount: 'Montant (€)',
            receiptNumber: 'Numéro de reçu',
            vatRate: 'Taux de TVA (%)',
            vatAmount: 'Montant TVA (€)',
            document: 'Document',
            image: 'Image',
            created: 'Créé',
            actions: 'Actions'
        },
        
        // Enum translations
        // BuchungsArt
        buchungsArt: {
            EINNAHME: 'Recette',
            AUSGABE: 'Dépense'
        },
        
        // BuchungsKategorie
        buchungsKategorie: {
            // Einnahmen
            VERKAUF: 'Ventes',
            DIENSTLEISTUNG: 'Services',
            ZINSEN: 'Intérêts',
            SONSTIGE_EINNAHMEN: 'Autres Recettes',
            
            // Ausgaben
            BUEROKOSTEN: 'Frais de Bureau',
            REISEKOSTEN: 'Frais de Voyage',
            MARKETING: 'Marketing',
            MIETE: 'Loyer',
            STROM: 'Électricité',
            TELEFON: 'Téléphone',
            VERSICHERUNG: 'Assurance',
            SOFTWARE_LIZENZ_GEBUEHR: 'Licence/Frais Logiciel',
            SERVER_SOFTWARE_HOSTING: 'Hébergement Serveur/Logiciel',
            SONSTIGE_AUSGABEN: 'Autres Dépenses'
        }
    },
    
    nl: {
        // Page title and overview
        title: 'Boekingskaarten overzicht',
        overview: 'Boekingskaarten overzicht',
        
        // Form labels and placeholders
        descriptionPlaceholder: 'Voer hier de boekingsbeschrijving in...',
        selectImage: 'Afbeelding selecteren (optioneel):',
        selectCategory: '-- Selecteer categorie --',
        selectBookingType: 'Boekingstype selecteren',
        noImage: '-- Geen afbeelding selecteren --',
        
        // Authentication and validation
        noAuthFound: 'Geen authenticatie gevonden. Log alstublieft in.',
        pleaseSelectBookingType: 'Selecteer een boekingstype.',
        pleaseEnterDate: 'Voer een datum in.',
        pleaseSelectCategory: 'Selecteer een categorie.',
        pleaseEnterDescription: 'Voer een beschrijving in.',
        pleaseEnterValidAmount: 'Voer een geldig bedrag in.',
        pleaseSelectDocument: 'Selecteer een document.',
        
        // Error messages
        errorLoadingCategories: 'Fout bij laden van categorieën. Probeer het later opnieuw.',
        errorLoadingImages: 'Fout bij laden van afbeeldingen. Probeer het later opnieuw.',
        errorLoadingBookings: 'Fout bij laden van boekingskaarten: ',
        errorDeleting: 'Fout bij verwijderen: ',
        
        // Empty states
        noBookings: 'Geen boekingskaarten beschikbaar',
        
        // Confirmations
        confirmDelete: 'Wilt u deze boeking echt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
        bookingDeleted: 'Boeking succesvol verwijderd',
        
        // Actions
        deleteBooking: 'Boeking verwijderen',
        
        // Evaluation section
        loadExistingEvaluations: 'Bestaande evaluaties laden',
        evaluationTitle: 'Leeg laten voor automatische titel',
        pleaseEnterDates: 'Voer zowel start- als einddatum in.',
        taxPayable: 'Te betalen BTW',
        taxRefundable: 'Terug te vorderen BTW',
        listBookings: 'Boekingen weergeven',
        noEvaluationsFound: 'Geen evaluaties gevonden.',
        existingEvaluations: 'Bestaande evaluaties',
        noBookingsInPeriod: 'Geen boekingen gevonden in de geselecteerde periode.',
        bookingsForCard: 'Boekingen voor',
        
        // Evaluation page
        evaluationsPageTitle: 'Boekingskaarten evaluaties',
        createNewEvaluation: 'Nieuwe evaluatie maken',
        periodType: 'Periode type:',
        dateFrom: 'Datum van:',
        dateTo: 'Datum tot:',
        titleOptional: 'Titel (optioneel):',
        createEvaluation: 'Evaluatie maken',
        
        // Period types
        periodTypes: {
            TAG: 'Dag',
            WOCHE: 'Week',
            MONAT: 'Maand',
            QUARTAL: 'Kwartaal',
            JAHR: 'Jaar',
            BENUTZERDEFINIERT: 'Aangepast'
        },
        
        // Evaluation display
        period: 'Periode:',
        type: 'Type:',
        to: 'tot',
        income: 'Inkomsten',
        expenses: 'Uitgaven',
        balance: 'Saldo',
        bookings: 'boekingen',
        totalBookings: 'boekingen totaal',
        outgoingVat: 'Uitgaande BTW',
        incomingVat: 'Inkomende BTW',
        vatBalance: 'BTW Saldo',
        vatFromIncome: 'BTW uit inkomsten',
        vatFromExpenses: 'BTW uit uitgaven',
        
        // Expandable booking view
        from: 'van',
        receipt: 'Bon:',
        document: 'Document:',
        image: 'Afbeelding:',
        clickFor: 'Klik voor',
        pdfView: 'PDF weergave',
        download: 'Downloaden',
        
        // PDF Report
        pdfReport: 'PDF Rapport',
        delete: 'Verwijderen',
        pdfReportCreating: 'PDF rapport wordt gemaakt...',
        
        // PDF Report Template
        evaluationReport: 'Boekhoudrapport',
        periodLabel: 'Periode:',
        createdOn: 'Gemaakt op:',
        bookingsDescending: 'Boekingen (gesorteerd op datum aflopend)',
        bookingsTotal: 'boekingen totaal',
        autoGenerated: 'Dit rapport werd automatisch gegenereerd door het Boekingskaarten Systeem',
        status: 'Status:',
        
        // Table headers for PDF
        pdfTableHeaders: {
            date: 'Datum',
            type: 'Type',
            category: 'Categorie',
            description: 'Beschrijving',
            amount: 'Bedrag',
            receiptNumber: 'Bonnummer',
            vatRate: 'BTW-tarief',
            vatAmount: 'BTW-bedrag',
            document: 'Document'
        },
        
        // PDF and popup
        popupBlocker: 'Popup-blocker voorkomt PDF-creatie. Sta popups toe voor deze site.',
        invalidDocument: 'Ongeldig document.',
        
        // Delete evaluation
        confirmDeleteEvaluation: 'Wilt u deze evaluatie echt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
        evaluationDeleted: 'Evaluatie succesvol verwijderd',
        errorDeletingEvaluation: 'Fout bij verwijderen van evaluatie: ',
        
        // Modal and form actions
        close: 'Sluiten',
        cannotChangeId: 'De ID kan niet worden gewijzigd',
        selectBookingTypeFirst: 'Selecteer eerst boekingstype',
        selectCategoryLabel: 'Categorie selecteren',
        
        // Additional error messages
        errorCreatingEvaluation: 'Fout bij creëren van evaluatie',
        errorLoadingEvaluations: 'Fout bij laden van evaluaties',
        errorDownloading: 'Fout bij downloaden',
        
        // Form labels
        createNewBookingCard: 'Nieuwe boekingskaart maken',
        bookingType: 'Boekingstype:',
        date: 'Datum:',
        category: 'Categorie:',
        description: 'Beschrijving:',
        amount: 'Bedrag (€):',
        receiptNumber: 'Bonnummer (optioneel):',
        vatRate: 'BTW-tarief (%) (optioneel):',
        vatAmount: 'BTW-bedrag (€) (optioneel):',
        receiptDocument: 'Bon document:',
        selectImageLabel: 'Afbeelding selecteren (optioneel):',
        save: 'Opslaan',
        chooseFile: 'Bestand kiezen',
        noFileSelected: 'Geen bestand geselecteerd',
        editBooking: 'Boeking bewerken',
        
        // Edit overlay
        editBookingTitle: '✏️ Boekingskaart bewerken',
        cancel: 'Annuleren',
        currentDocument: 'Huidig document:',
        cannotChangeIdDescription: 'De ID kan niet worden gewijzigd',
        
        // Form labels for edit overlay
        editLabels: {
            id: 'ID',
            date: 'Datum',
            description: 'Beschrijving',
            amount: 'Bedrag (€)',
            receiptNumber: 'Bonnummer',
            vatRate: 'BTW-tarief (%)',
            vatAmount: 'BTW-bedrag (€)',
            bookingType: 'Boekingstype',
            category: 'Categorie',
            receiptDocument: 'Bon document',
            imageOptional: 'Afbeelding (optioneel)'
        },
        
        // Overview page
        overviewTitle: 'Boekingskaarten overzicht',
        loading: 'Boekingskaarten laden...',
        noAuthForTable: 'Geen authenticatie gevonden. Log alstublieft in.',
        errorLoadingBookingsTable: 'Fout bij laden van boekingskaarten',
        
        // Table headers
        tableHeaders: {
            id: 'ID',
            date: 'Datum',
            bookingType: 'Boekingstype',
            category: 'Categorie',
            description: 'Beschrijving',
            amount: 'Bedrag (€)',
            receiptNumber: 'Bonnummer',
            vatRate: 'BTW-tarief (%)',
            vatAmount: 'BTW-bedrag (€)',
            document: 'Document',
            image: 'Afbeelding',
            created: 'Aangemaakt',
            actions: 'Acties'
        },
        
        // Enum translations
        // BuchungsArt
        buchungsArt: {
            EINNAHME: 'Inkomsten',
            AUSGABE: 'Uitgaven'
        },
        
        // BuchungsKategorie
        buchungsKategorie: {
            // Einnahmen
            VERKAUF: 'Verkoop',
            DIENSTLEISTUNG: 'Dienstverlening',
            ZINSEN: 'Rente',
            SONSTIGE_EINNAHMEN: 'Overige Inkomsten',
            
            // Uitgaben
            BUEROKOSTEN: 'Kantoorkosten',
            REISEKOSTEN: 'Reiskosten',
            MARKETING: 'Marketing',
            MIETE: 'Huur',
            STROM: 'Elektriciteit',
            TELEFON: 'Telefoon',
            VERSICHERUNG: 'Verzekering',
            SOFTWARE_LIZENZ_GEBUEHR: 'Software Licentie/Kosten',
            SERVER_SOFTWARE_HOSTING: 'Server/Software Hosting',
            SONSTIGE_AUSGABEN: 'Overige Uitgaven'
        }
    }
};