ktor:
   development: false
   application:
       modules:
           - com.shut.ApplicationKt.module
   deployment:
       port: 5000
       host: 0.0.0.0
       maxResponseSize: 500000000

postgres:
 # Local PostgreSQL on EC2 instance
 url: "jdbc:postgresql://localhost:5432/learningcards"
 user: "learningcards_user"
 password: "your_secure_password_here"
 domain: "http://your-ec2-ip/"
 audience: "learning-cards-audience"
 realm: "Learning Cards Demo"

fileStorage:
 type: local
 local:
   basePath: "/opt/learningcards/storage"
   subdirectories:
     images: "images"
     documents: "documents"
     thumbnails: "thumbnails"

logging:
 level: INFO
 appenders:
   - name: STDOUT
     pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
   - name: FILE
     pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
     fileName: "/opt/learningcards/logs/application.log"