ktor:
    development: false
    application:
        modules:
            - com.shut.ApplicationKt.module
    deployment:
        port: ${PORT:5000}
        host: 0.0.0.0
        maxResponseSize: 500000000

postgres:
  # Aurora Serverless v2 connection - will be auto-scaled based on demand
  url: "jdbc:postgresql://${DB_HOST:your-aurora-cluster.cluster-xxxxxxxx.region.rds.amazonaws.com}:${DB_PORT:5432}/${DB_NAME:learningcards}"
  user: "${DB_USER:postgres}"
  password: "${DB_PASSWORD:}"
  domain: "${JWT_DOMAIN:https://your-domain.com/}"
  audience: "${JWT_AUDIENCE:learning-cards-audience}"
  realm: "${JWT_REALM:Learning Cards App}"

fileStorage:
  type: s3
  s3:
    bucketName: "${S3_BUCKET_NAME:m3-cas1}"
    region: "${AWS_REGION:eu-central-1}"
    # AWS Credentials will be provided via IAM roles or environment variables
    accessKeyId: "${AWS_ACCESS_KEY_ID:}"
    secretAccessKey: "${AWS_SECRET_ACCESS_KEY:}"
    sessionToken: "${AWS_SESSION_TOKEN:}"

logging:
  level: INFO
  appenders:
    - name: STDOUT
      pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"