ktor:
    development: on
    application:
        modules:
            - com.shut.ApplicationKt.module
    deployment:
        port: 5000
        host: 0.0.0.0
        maxResponseSize: 500000000
        watch:
          - build/classes/kotlin/main # Beispielpfad
          - build/resources/main # Beispielpfad


postgres:
  url: "jdbc:postgresql://localhost:5432/learningcards"
  user: "postgres"
  password: "afthco99"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"


fileStorage:
  type: local
  local:
    basePath: "/opt/learningcards/content-store"
    subdirectories:
      images: "images"
      documents: "documents"
      thumbnails: "thumbnails"

  s3:
    bucketName: m3-cas1
    region: eu-central-1
    # AWS Credentials (will use environment variables or AWS credential chain)
    # Leave empty to use AWS default credential provider chain
    accessKeyId: ""
    secretAccessKey: ""
    sessionToken: ""

smtp:
  host: "smtp.mailbox.org"
  port: 465
  username: "mag.stefan.hutter@m3-works.com"
  password: "r!w-A8Db$wd?bEA"
  fromEmail: "mag.stefan.hutter@m3-works.com"
  fromName: "Learning Cards"
  enableTLS: true
  enableAuth: true


logging:
  level: INFO
  appenders:
    - name: STDOUT
      pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    - name: FILE
      pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      fileName: "/opt/learningcards/logs/application.log"